### ISSUE TITLE
Path agnostic example

### ISSUE THREAD

**Issue by alberto-lazari** [SkiFire13/typst-prooftree#1]
https://github.com/SkiFire13/typst-prooftree/blob/ade1edd629429d02b5884a5efd8ed48b93faf9d8/README.md?plain=1#L12

I would put a more universal path in the example, such as:
```js
#import "typst-prooftree/prooftree.typ": *
```

which is the kind of path you use when you include a Typst dependency as git submodule and you have your `main.typ` in the root of the repo.

Alternatively you should put a
```js
#import "path/to/prooftree.typ": *
```

which is always ugly imo

**Comment by SkiFire13** [comment]
Thanks, I think I'm gonna opt for the alternative which looks more general and less misunderstandable.
