### ISSUE TITLE
`rule(n: 0)` not working

### ISSUE THREAD

**Issue by alberto-lazari** [SkiFire13/typst-prooftree#4]
When trying to define a simple tree as a rule without axioms (`n: 0`) the compiler returns the following:

```
error: unexpected argument
    ┌─ /typst-prooftree/prooftree.typ:177:24
    │
177 │     return axiom(label, root)
    │                         ^^^^
```

The issue may probably be that `axiom()` doesn't actually support a label?

**Comment by alberto-lazari** [comment]
Also, it would make sense, as suggested in `prooftree.typ`, that using `n: 0` produces an axiom with the line and no premises. At that point it would make sense to use an eventually provided label.

This way it would become a shorthand for
```js
#prooftree(
  axiom(""),
  rule(label: /* ... /*, /* ... */)
)
```

**Comment by SkiFire13** [comment]
The linked commit fixes the error, but I've come back and changed `rule(n: 0, ...)` to actually draw the line. The relative section of code make kinda strong assumptions on the presence of subtrees, so it's likely that some bug may have slipped through. Let me know if you find any bug.

**Comment by alberto-lazari** [comment]
Seems to work fine
