### ISSUE TITLE
Add `line-stroke` and `label.padding` to readme

### ISSUE THREAD

**Issue by alberto-lazari** [SkiFire13/typst-prooftree#5]
Oops, PR #2 didn't update `README.md` with a description of the new parameter

**Comment by SkiFire13** [comment]
PR #3 also forgot to update the README with the new `label.padding` parameter

**Comment by alberto-lazari** [comment]
#6 didn't automatically close the issue, I suppose it's due to the fact that I didn't write exactly "fixes #5"
