### ISSUE TITLE
Maximum call depth easily exceeded in Typst 0.10.0

### ISSUE THREAD

**Issue by emosy** [SkiFire13/typst-prooftree#7]
When using Typst compiler version 0.10.0 (where the maximum call depth was decreased from 256 to 64), any straight line tree with more than 8 rules in a row will cause the maximum call depth to be exceeded.

Example:
```typst
#prooftree(
  axiom("1"),
  rule("2"),
  rule("3"),
  rule("4"),
  rule("5"),
  rule("6"),
  rule("7"),
  rule("8"),
  rule("9"),
)
```

Output of `typst c example.typ`:
```
error: maximum layout depth exceeded
 = hint: try to reduce the amount of nesting in your layout

help: error occurred in this call of function `measure`
    ┌─ prooftree.typ:209:22
    │
209 │       let width(it) = measure(it, styles).width
    │                       ^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `width`
    ┌─ prooftree.typ:239:30
    │
239 │       let wbranches_nolabel = width(branches) - children_label_wleft - children_label_wright
    │                               ^^^^^^^^^^^^^^^

help: error occurred in this function call
    ┌─ prooftree.typ:112:17
    │  
112 │         let elem = rule_func(
    │ ╭──────────────────^
113 │ │         settings,
114 │ │         styles,
115 │ │         stack.slice(stack.len() - to_pop)
116 │ │       )
    │ ╰───────^
```

**Comment by SkiFire13** [comment]
I see, currently the library is creating a stack for each level where the bottom element is the bottom-most line and the top element is the rest of the tree, which itself contains a recursive stack etc etc. This means the more layers you add the more nested it becomes, which now more easily triggers the error (you could probably still hit the error before with a tree 4x deeper than yours).

I can see a potential solution by manually calculate where each element should go to and then placing them all at once. It should be feasible, though it would require me to rewrite a large part of the library. I'll see what I can do.

**Comment by Enter-tainer** [comment]
typst 0.11.0 introduces context expression. will this help?

**Comment by SkiFire13** [comment]
> typst 0.11.0 introduces context expression. will this help?

I only gave it a quick look since I didn't have too much time in the last weeks, it looks like it may help a bit, but I'll still need to completly rework how the library draws the tree.

**Comment by SkiFire13** [comment]
I reworked how the library performs layouting and it no longer produces recursive content trees, which was the source of the error, so this should now be fixed.

**Comment by emosy** [comment]
🙌 Thank you @SkiFire13
