### ISSUE TITLE
Right side labels are broken with new version

### ISSUE THREAD

**Issue by emosy** [SkiFire13/typst-prooftree#8]
Hello,

Thank you for reworking the implementation to allow infinite nesting. However, the reworked version now does not support right labels.

```typst
#prooftree(
  label: (side: right, padding: 1em),
  axiom("A"),
  rule("B", label: "right with 1em padding")
)

#prooftree(
  label: (side: left, padding: 1em),
  axiom("A"),
  rule("B", label: "left with 1em padding")
)
```

As you can see from this image, the label on the right simply clips into the prooftree. I tried debugging it but was unable to determine a quick fix. One thing I figured out is that `label_left` and `label_right` always seem to be equal to 0pt in my debugging.

![image](https://github.com/SkiFire13/typst-prooftree/assets/27254405/dbab1d5c-bcd6-4a80-b259-eb1a6e85735c)

**Comment by SkiFire13** [comment]
Should be fixed now, let me know if there's something else I missed.
